### ISSUE TITLE
#2 Implement method 'def on_fingerprint' in 'class Update_residents'

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#36]
@Justinjay282 

- [X] Alle fulfilled

**Comment by Justinjay282** [comment]
sir, @WK-GiHu, 
> * [x]  Please, explain how `Enter` works, when does this event fire?
   
The "Enter" works if the cursor entered the widget. It will immediately call the method if the cursor entered the widget. that's why the size of my label is the same size as the window so after clicking the `update button` it will immediately fire.

> * [x]  Implement the `def on_destroy(self, event):` for `class Update_residents`.
>   Do accordingly like here: [doing-tasks-when-a-tkinter-application-is-closed](https://stackoverflow.com/questions/48603066)
>   Add
>   ```
>         # Change back to continius SEARCH mode
>         print('set mode SEARCH')
>         self.app.fp.set_mode(FingerprintDevice.SEARCH)
>   ```

I edited the code in the `repository` sir. I also deleted the code block you made me delete and save it for future uses.
Also, I put 
https://github.com/Justinjay282/qwerty/blob/f1c29403c15059e3407258875640a3c7e054a83f/update_resident_fingerprint.py#L59
( if the `toplevel` was destroyed it will back to login)

**Comment by WK-GiHu** [comment]
@Justinjay282 

You didn't fulfill all requested changes, read againg https://github.com/Justinjay282/qwerty/issues/36#issue-581413624

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've committed the changes in `update_residents_fingerprint.py` 
I'm confused here:
> Obey where fp and REGISTER are comming from, adapt accordingly.

and when I tried to run the code I'm getting this error:
```
Traceback (most recent call last):
  File "/home/pi/Thesis/update_residents_revised.py", line 185, in <module>
    Update_residents().mainloop()
TypeError: __init__() missing 1 required positional argument: 'app'
```
run in `update_residents.py`
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/Thesis_Revised2.py", line 1402, in Update_Residents
    update_residents.Update_residents(self)
TypeError: __init__() takes 1 positional argument but 2 were given
```
run in `Kiosk_Main.py`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>`Update_residents().mainloop()`
>'TypeError: __init__() missing 1 required positional argument: 'app''

If you want to test this module by it self, you have to provide a proper environment. Look at `FingerprintDevice.__main__` to get at clue.

You need:
1. `root = ...`
2. `root.fp = Finger...`
3. `Update_residents(root)
4. `root.mainloop()`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I'm confused here:
>> Obey where fp and REGISTER are comming from, adapt accordingly.

There is no local `fp` here like in `__main__`.
Where is `fp` defined?
You have to prepend with the `class reference`

---

Still not fulfilled, read again https://github.com/Justinjay282/qwerty/issues/36#issue-581413624

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I don't think I did it all right. I will do it slowly sir, can you check what I did? I can't run it in my `Main_Kiosk.py` also change the `super().__init__(app)`

especially here:
>Obey where fp and REGISTER are comming from, adapt accordingly.

should I put `fp = FingerprintThread(self)`
in `class Update_residents` `__init__`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>>Obey where fp and REGISTER are comming from, adapt accordingly.
>should I put `fp = FingerprintThread(self)`
in `class Update_residents __init__`

No, no new instance of `FingerprintDevice`.
This leads to error: `multiple access`.
Therefore we have changed `Kiosk_Main.py`
https://github.com/Justinjay282/qwerty/blob/edf1a855de3568cac8bbf32f897138443cde7274/Kiosk_Main.py#L129
  and
https://github.com/Justinjay282/qwerty/blob/edf1a855de3568cac8bbf32f897138443cde7274/Kiosk_Main.py#L224

>>Obey where fp and REGISTER are comming from, adapt accordingly.

Where is `REGISTER` defined?
You used it already here:
https://github.com/Justinjay282/qwerty/blob/5eec8c6dba8fc75d89de6bd5bfe1e124bfca7e3b/update_resident_fingerprint.py#L168

**Comment by WK-GiHu** [comment]
@Justinjay282 

### Where is the `def Updated_fingerprint(...` gone?
No more event `<Enter>`?

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> ### Where is the `def Updated_fingerprint(...` gone?
> No more event `<Enter>`?

sir @WK-GiHu, yes sir I removed it. I only used it in order for my fingerprint to scan without using a button. Since the register will not freeze the code I think I can remove it. 
I'm running, the `update_resident` in `Kiosk_Main.py` but I'm getting an error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/Thesis_Revised2.py", line 1402, in Update_Residents
    update_residents.Update_residents(self)
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

> update_residents.Update_residents(self)
TypeError: __init__() takes 1 positional argument but 2 were given

Can't follow this error, may i see the output of 
```
print(type(update_residents.Update_residents))
```
just before the line
```
update_residents.Update_residents(self)
```

**Comment by Justinjay282** [comment]
sir, @WK-GiHu, It's the output sir
```
<class 'type'>
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

I have update my comment, verify `__init__`

**Comment by Justinjay282** [comment]
@WK-GiHu yes sir. I have
```
    def __init__(self, app):
        super().__init__(app)
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>. I have
>```
    def __init__(self, app):
        super().__init__(app)
```
Shame on you
How does this look ...
https://github.com/Justinjay282/qwerty/blob/5eec8c6dba8fc75d89de6bd5bfe1e124bfca7e3b/update_resident_fingerprint.py#L15

**Comment by Justinjay282** [comment]
sir @WK-GiHu I'm sorry sir. I'm doing my best. I remove the `app` in `super().__init__(app)` and it works. but it became laggy...

**Comment by WK-GiHu** [comment]
@Justinjay282 

>but it became laggy...

Wher did you start from?

Still not fulfilled, read again https://github.com/Justinjay282/qwerty/issues/36#issue-581413624

**Comment by WK-GiHu** [comment]
@Justinjay282 

We are missing
https://github.com/Justinjay282/qwerty/blob/edf1a855de3568cac8bbf32f897138443cde7274/Kiosk_Main.py#L130

- [ ] Inser after line 62 ...
 https://github.com/Justinjay282/qwerty/blob/5eec8c6dba8fc75d89de6bd5bfe1e124bfca7e3b/update_resident_fingerprint.py#L62
  ```
  self.app.bind('<<FINGERPRINT>>', self.on_fingerprint)
  ```

- [ ] Insert before line 167
https://github.com/Justinjay282/qwerty/blob/5eec8c6dba8fc75d89de6bd5bfe1e124bfca7e3b/update_resident_fingerprint.py#L167
  ```
  self.app.bind('<<FINGERPRINT>>', self.app.on_fingerprint)
  ```
### Obey the different statement!

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I added the `super().__init__(app)` and it's working now.
Maybe the reason is the lag... I don't know what happened. I think the image data in the database too much and it's a reason why it's lag. 

I've edited the code `update_resident_fingerprint.py` can you check it sir. if. I can't check the
> Obey where fp and REGISTER are comming from, adapt accordingly.
I still confused sir.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Still not fulfilled: https://github.com/Justinjay282/qwerty/issues/36#issue-581413624, read again
Typo, read the [comment](https://github.com/Justinjay282/qwerty/issues/36#issuecomment-599226707) again

>Obey where fp and REGISTER are comming from, adapt accordingly.
>I still confused sir.

Look at this statement
https://github.com/Justinjay282/qwerty/blob/b54d05e46c90f86c09bf56a20bcae9f84e34d90d/update_resident_fingerprint.py#L160

Write the others, using `fp.` accordinly

**Comment by Justinjay282** [comment]
sir @WK-GiHu, so I will do `self.app.fp`? 
I edited the file sir `update_residents_fingerprint.py` can you check it sir?

**Comment by WK-GiHu** [comment]
@Justinjay282 

OK, one left, read again https://github.com/Justinjay282/qwerty/issues/36#issue-581413624

**Comment by Justinjay282** [comment]
sir, @WK-GiHu 
> 
> * [ ]  Copy from `FingerprintDevice.__main__` function `def on_fingerprint`.
>   **Obey, here it is a `class methode`!**
>   https://github.com/Justinjay282/qwerty/blob/57b644f152537206d9c1fae75cee4b53b53a2abf/update_resident_fingerprint.py#L108
I don't get it sorry sir,...
Copy from `FingerprintDevice.py.` `__main__`  def on_fingerprint(event):...`
so I'll copy this
```
    def on_fingerprint(event):
        print('on_fingerprint()  template_id={}'.format(event.state))
        
        if event.state >= 0:
            global template_id
            template_id = event.state
            btn2.configure(text=btn2._text.format(template_id))
```
from `FingerprintDevice.py`?

**Comment by WK-GiHu** [comment]
@Justinjay282 

You copy is ok, but read again https://github.com/Justinjay282/qwerty/issues/36#issuecomment-599231960

**Comment by Justinjay282** [comment]
sir @WK-GiHu, so I'll change the `def` to `class` sir...? 

or... I'll do `@classmethod`?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>or... I'll do @classmethod?

NO, you need the `self`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I'm sorry. I get it now since all methods of class have a `self` and I misunderstood it and think of a `@classmethod` literally. ugg I'm so dumbbbb!

**Comment by WK-GiHu** [comment]
@Justinjay282 

You reverted a allready OK statement, read again https://github.com/Justinjay282/qwerty/issues/36#issuecomment-599231960

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> * [ ]  Revert this back, you have changed the allready OK statement
>   I wrote: ***Obey the different statements**, now you have copied the on from `__init__`.
>   https://github.com/Justinjay282/qwerty/blob/57b644f152537206d9c1fae75cee4b53b53a2abf/update_resident_fingerprint.py#L158
sir @WK-GiHu,
can you explain it again sir? I'm sorry I'm quite confused.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Should read: 
```
self.app.bind('<<FINGERPRINT>>', self.app.on_fingerprint)
```

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've committed the changes in `update_residents_fingerprint.py`

**Comment by WK-GiHu** [comment]
@Justinjay282 

We hava a logic quirk.
The `FingerprintDevice` is allready sensitve.
This leads to: touching the **Finge Sensor** before touching `Button Update` we get a `SEARCH` event .
Do you see any problem herein?

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] Please add a comment above line 146 to explain why this condition lead to delete a template.
https://github.com/Justinjay282/qwerty/blob/12b1403b87caa034318b87cb765a19d90cbd2a21/update_resident_fingerprint.py#L146

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> We hava a logic quirk.
> The `FingerprintDevice` is all the time sensitive.
> This leads to: touching the **Finge Sensor** before touching `Button Update` we get a `SEARCH` event .
> Do you see any problem herein?

sir @WK-GiHu, I'm encountering this error:
```Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/update_residents_revised.py", line 161, in on_destroy
    self.app.fp.set_mode(FingerprintDevice.SEARCH)
NameError: name 'FingerprintDevice' is not defined
set mode SEARCH
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Thesis/update_residents_revised.py", line 161, in on_destroy
    self.app.fp.set_mode(FingerprintDevice.SEARCH)
NameError: name 'FingerprintDevice' is not defined
```
after registering a finger two times, the messagebox will appear. "registered successful" but after closing. I got that error

**Comment by WK-GiHu** [comment]
@Justinjay282 

>NameError: name 'FingerprintDevice' is not defined

Yes, my bad.
Rename all `FingerprintDevice` to `FingerprintThread` except the `import ...` one

**Comment by Justinjay282** [comment]
sir @WK-GiHu I edited the code in `update_residents_fingerprint.py` the error disappeared.
I can register a finger. but I noticed that I'm only registering one time. not twice to check if the finger registered twice.

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] There is no `template_id`, see your previous version, there you got the Template ID from the `Treeview`.
Add this part, accordingly!
https://github.com/Justinjay282/qwerty/blob/8f61edbe2cc27fe8eb64411cd7bf7d8866676eee/update_resident_fingerprint.py#L147

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I can register a finger. but I noticed that I'm only registering one time. not twice to check if the finger registered twice.

Confirm with `FingerprintDevice.__main__`

**Comment by Justinjay282** [comment]
sir @WK-GiHu I edited the code. Can you check if what I did is right? Also, a messagebox just prompt `Fingerprint already registered` but there's no template recorded in the fingerprint scanner itself.

>Confirm with FingerprintDevice.__main__

will do so

**Comment by WK-GiHu** [comment]
@Justinjay282 

Obey, if you get the `print('set mode SEARCH')` before registering, i think you get a `SEARCH` event.

- [ ] This is invalid, there is no `event....` here.
 
https://github.com/Justinjay282/qwerty/blob/fdd4620c02f29a2272f7ccbd6ab637349f80d8f2/update_resident_fingerprint.py#L146

You have to rebuild this from your first version:
```
 ## Tries to delete the template of the finger
            positionNumber = list_values[12]
            positionNumber = int(positionNumber)
            print(positionNumber)
            if (f.deleteTemplate(positionNumber) == True):
```

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I erased the `event....` and included the
```
            positionNumber = list_values[12]
            positionNumber = int(positionNumber)
            print(positionNumber)
```
can you check my `Main_Kiosk.py` and `update_resident_fingerprint.py` if I did something wrong?
I'll also go offline, I haven't got any sleep. I'll continue this right away when I wake up. I feel like it's near to its completion. thank you so much for helping me. I'm really dizzy now.

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] Please add a comment above line 146 to explain why this condition lead to delete a template.
https://github.com/Justinjay282/qwerty/blob/12b1403b87caa034318b87cb765a19d90cbd2a21/update_resident_fingerprint.py#L146

- [ ] This will fail with name error and variable used before defined.
  There is no `template_id`, but i recommend to rename `positionNumber` to `template_id`.
  https://github.com/Justinjay282/qwerty/blob/ec01893949fb2294fdd7a7b11e706ac03910ff91/update_resident_fingerprint.py#L148-L151

---

I'm sure,  your `Button(text = "Update Fingerprint")` get not fired.
Therefore the methode `def Update_fingerprint` are not called, which lead to what i described here: [logic quirk](https://github.com/Justinjay282/qwerty/issues/36#issuecomment-599236703).
The `REGISTER` mode are not active, you get a `SEARCH` sequence and event.

- [ ] Verify if you use
https://github.com/Justinjay282/qwerty/blob/ec01893949fb2294fdd7a7b11e706ac03910ff91/update_resident_fingerprint.py#L14
without `(app)`, may lead to not getting the event.
